### ISSUE TITLE
请问是否能提供完整的示例代码及相关Maven配置？

### ISSUE THREAD

**Issue by liuyu2018** [meta-soul/LakeSoul#72]
我尝试在内部网络里搭建一个LakeSoul的示例，我在Windows上搭建Hadoop、Spark、Java、Scala，但是在使用Scala运行提供的示例代码时异常，提示AWS证书问题（No AWS Credentials provided by SimpleAWSCredentialsProvider EnvironmentVariableCredentialsProvider InstanceProfileCredentialsProvider）,查询资料后，需要往AWS进行权限认证，但是这和我们离线环境下使用相悖，是否是我这边的尝试有问题？我一开始也是在CentOS7上进行环境搭建，也是遇到了一系列的问题，在国内的博客上也几乎没有相关环境的搭建教程，请问是否能够提供一个完整的项目示例搭建教程？我们想往国内开源项目转，但是资料真的很匮乏。

**Comment by moresun** [comment]
使用文档  https://github.com/meta-soul/LakeSoul/wiki/%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3

文档中使用了  val tablePath = "s3a://bucket-name/table/path/is/also/table/name" 有前缀s3a，会走aws路径；若是要读取本地直接去掉 val tablePath = "/bucket-name/table/path/is/also/table/name" 或者把s3a换成file val tablePath = "file://bucket-name/table/path/is/also/table/name"；
若是使用hdfs 将 s3a换成 hdfs:// 即可，不必须使用hdfs

我们官网 https://www.dmetasoul.com/ 可以添加微信群   群名称 元灵数智—LakeSoul—交流群
二维码
![lakesoul](https://user-images.githubusercontent.com/29471995/184057425-ee5b515e-8e80-4a72-b3f7-e58e4a388fc9.jpg)

也可以从我们发的文章里面找到群  
https://mp.weixin.qq.com/s/X12CiDgL5kRE4uBPOu15aw

我们会在群里面详细解答，其他文档我们也会尽快补齐

**Comment by dmetasoul01** [comment]
@liuyu2018 你好，如果在本地测试可以直接使用 file:// 开头的本地目录作为表路径，这样就不需要配置 S3 相关的配置项。
本地测试可以通过 docker 的方式启动 PostgreSQL ，可以参考：https://github.com/meta-soul/LakeSoul/wiki/%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B
启动后可以参考 https://github.com/meta-soul/LakeSoul/wiki/%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3 测试验证。
也欢迎加入交流群，我们会有专人协助和回答您的问题。

**Comment by liuyu2018** [comment]
> 使用文档 https://github.com/meta-soul/LakeSoul/wiki/%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3
> 
> 文档中使用了 val tablePath = "s3a://bucket-name/table/path/is/also/table/name" 有前缀s3a，会走aws路径；若是要读取本地直接去掉 val tablePath = "/bucket-name/table/path/is/also/table/name" 或者把s3a换成file val tablePath = "file://bucket-name/table/path/is/also/table/name"； 若是使用hdfs 将 s3a换成 hdfs:// 即可，不必须使用aws
> 
> 我们官网 https://www.dmetasoul.com/ 可以添加微信群 群名称 元灵数智—LakeSoul—交流群 二维码 ![lakesoul](https://user-images.githubusercontent.com/29471995/184057425-ee5b515e-8e80-4a72-b3f7-e58e4a388fc9.jpg)
> 
> 也可以从我们发的文章里面找到群 https://mp.weixin.qq.com/s/X12CiDgL5kRE4uBPOu15aw
> 
> 我们会在群里面详细解答，其他文档我们也会尽快补齐

好的，感谢回复！

**Comment by liuyu2018** [comment]
> @liuyu2018 你好，如果在本地测试可以直接使用 file:// 开头的本地目录作为表路径，这样就不需要配置 S3 相关的配置项。 本地测试可以通过 docker 的方式启动 PostgreSQL ，可以参考：https://github.com/meta-soul/LakeSoul/wiki/%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B 启动后可以参考 https://github.com/meta-soul/LakeSoul/wiki/%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3 测试验证。 也欢迎加入交流群，我们会有专人协助和回答您的问题。

好的，谢谢！
